name: clinics_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: fonts\SFPRODISPLAYBLACKITALIC.OTF
        - asset: fonts\SFPRODISPLAYBOLD.OTF
        - asset: fonts\SFPRODISPLAYHEAVYITALIC.OTF
        - asset: fonts\SFPRODISPLAYLIGHTITALIC.OTF
        - asset: fonts\SFPRODISPLAYMEDIUM.OTF
        - asset: fonts\SFPRODISPLAYREGULAR.OTF
        - asset: fonts\SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: fonts\SFPRODISPLAYTHINITALIC.OTF
        - asset: fonts\SFPRODISPLAYULTRALIGHTITALIC.OTF
  uses-material-design: true
  assets:
    - images/logo-icon-square.png
    - images/
