name: clinics_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: fonts\SFPRODISPLAYBLACKITALIC.OTF
        - asset: fonts\SFPRODISPLAYBOLD.OTF
        - asset: fonts\SFPRODISPLAYHEAVYITALIC.OTF
        - asset: fonts\SFPRODISPLAYLIGHTITALIC.OTF
        - asset: fonts\SFPRODISPLAYMEDIUM.OTF
        - asset: fonts\SFPRODISPLAYREGULAR.OTF
        - asset: fonts\SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: fonts\SFPRODISPLAYTHINITALIC.OTF
        - asset: fonts\SFPRODISPLAYULTRALIGHTITALIC.OTF
  uses-material-design: true
  assets:
    - public/images/search.png
    - public/images/user.png
    - public/images/doctor.png
    - public/images/doctor2.png
    - public/images/doctor3.png
    - public/images/card-tag.png
    - public/images/card-tag2.png
    - public/images/card-tag3.png
    - public/images/cardprod.png
    - public/images/ushi.png
    - public/images/ber.png
    - public/images/skid.png
    - public/images/analiz.png
    - public/images/chem.png
    - public/images/daig.png
    - public/images/cons.png
    - public/images/proc.png

    - images/logo-icon-square.png
    - images/
